// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SL_Bullion.DAL;

#nullable disable

namespace SL_Bullion.Migrations
{
    [DbContext(typeof(BullionDbContext))]
    [Migration("20260610072049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SL_Bullion.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firmName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<string>("gst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isRegister")
                        .HasColumnType("bit");

                    b.Property<string>("loginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("margin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tradeAccess")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblAccount");
                });

            modelBuilder.Entity("SL_Bullion.Models.Bank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("ifscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("tblBank");
                });

            modelBuilder.Entity("SL_Bullion.Models.BankLogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblBankLogo");
                });

            modelBuilder.Entity("SL_Bullion.Models.BankRate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<double>("conversionGold")
                        .HasColumnType("float");

                    b.Property<double>("conversionSilver")
                        .HasColumnType("float");

                    b.Property<double>("customDutyGold")
                        .HasColumnType("float");

                    b.Property<double>("customDutySilver")
                        .HasColumnType("float");

                    b.Property<double>("divisionGold")
                        .HasColumnType("float");

                    b.Property<double>("divisionSilver")
                        .HasColumnType("float");

                    b.Property<double>("gstGold")
                        .HasColumnType("float");

                    b.Property<double>("gstSilver")
                        .HasColumnType("float");

                    b.Property<double>("interBankGold")
                        .HasColumnType("float");

                    b.Property<double>("interBankSilver")
                        .HasColumnType("float");

                    b.Property<double>("marginGold")
                        .HasColumnType("float");

                    b.Property<double>("marginSilver")
                        .HasColumnType("float");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiplyGold")
                        .HasColumnType("float");

                    b.Property<double>("multiplySilver")
                        .HasColumnType("float");

                    b.Property<double>("premiumGold")
                        .HasColumnType("float");

                    b.Property<double>("premiumSilver")
                        .HasColumnType("float");

                    b.Property<string>("spotTypeGold")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spotTypeSilver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblBankRate");
                });

            modelBuilder.Entity("SL_Bullion.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDisplay")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblCategory");
                });

            modelBuilder.Entity("SL_Bullion.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblCity");
                });

            modelBuilder.Entity("SL_Bullion.Models.CloseOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("closeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dealNo")
                        .HasColumnType("int");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("editorderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("exchange")
                        .HasColumnType("float");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("margin")
                        .HasColumnType("float");

                    b.Property<DateTime>("orderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("premium")
                        .HasColumnType("float");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<double?>("rateOpen")
                        .HasColumnType("float");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("symbolId")
                        .HasColumnType("int");

                    b.Property<string>("symbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tradeType")
                        .HasColumnType("int");

                    b.Property<double>("volume")
                        .HasColumnType("float");

                    b.Property<double?>("volumeOpen")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("tblCloseOrder");
                });

            modelBuilder.Entity("SL_Bullion.Models.CloseOrderCoin", b =>
                {
                    b.Property<int>("OpenOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpenOrderID"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CloseDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ClosePrice")
                        .HasColumnType("float");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DealNo")
                        .HasColumnType("bigint");

                    b.Property<double>("Exchange")
                        .HasColumnType("float");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenTradeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SymbolID")
                        .HasColumnType("int");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float");

                    b.Property<string>("TradeFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("OpenOrderID");

                    b.ToTable("tblCloseOrderCoin");
                });

            modelBuilder.Entity("SL_Bullion.Models.Coin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("buyCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("buyPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<int>("coinId")
                        .HasColumnType("int");

                    b.Property<double>("coinStock")
                        .HasColumnType("float");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("division")
                        .HasColumnType("float");

                    b.Property<double>("gst")
                        .HasColumnType("float");

                    b.Property<int>("index")
                        .HasColumnType("int");

                    b.Property<bool>("isStock")
                        .HasColumnType("bit");

                    b.Property<bool>("isView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiply")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("sellCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("sellPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblCoin");
                });

            modelBuilder.Entity("SL_Bullion.Models.CoinBank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<double>("conversionGold")
                        .HasColumnType("float");

                    b.Property<double>("conversionSilver")
                        .HasColumnType("float");

                    b.Property<double>("customDutyGold")
                        .HasColumnType("float");

                    b.Property<double>("customDutySilver")
                        .HasColumnType("float");

                    b.Property<double>("divisionGold")
                        .HasColumnType("float");

                    b.Property<double>("divisionSilver")
                        .HasColumnType("float");

                    b.Property<double>("gstGold")
                        .HasColumnType("float");

                    b.Property<double>("gstSilver")
                        .HasColumnType("float");

                    b.Property<double>("interBankGold")
                        .HasColumnType("float");

                    b.Property<double>("interBankSilver")
                        .HasColumnType("float");

                    b.Property<double>("marginGold")
                        .HasColumnType("float");

                    b.Property<double>("marginSilver")
                        .HasColumnType("float");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiplyGold")
                        .HasColumnType("float");

                    b.Property<double>("multiplySilver")
                        .HasColumnType("float");

                    b.Property<double>("premiumGold")
                        .HasColumnType("float");

                    b.Property<double>("premiumSilver")
                        .HasColumnType("float");

                    b.Property<string>("spotTypeGold")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spotTypeSilver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblCoinBank");
                });

            modelBuilder.Entity("SL_Bullion.Models.CoinInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblCoinInfo");
                });

            modelBuilder.Entity("SL_Bullion.Models.Contact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bannerApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bannerWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("email1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("freezInner")
                        .HasColumnType("int");

                    b.Property<int>("freezOuter")
                        .HasColumnType("int");

                    b.Property<string>("goldCoinHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("goldDifferance")
                        .HasColumnType("int");

                    b.Property<bool>("isBuy")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoinRate")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoinTrade")
                        .HasColumnType("bit");

                    b.Property<bool>("isGoldCoinHeader")
                        .HasColumnType("bit");

                    b.Property<bool>("isHedge")
                        .HasColumnType("bit");

                    b.Property<bool>("isHigh")
                        .HasColumnType("bit");

                    b.Property<bool>("isLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("isLow")
                        .HasColumnType("bit");

                    b.Property<bool>("isRate")
                        .HasColumnType("bit");

                    b.Property<bool>("isSell")
                        .HasColumnType("bit");

                    b.Property<bool>("isSilverCoinHeader")
                        .HasColumnType("bit");

                    b.Property<bool>("isTrade")
                        .HasColumnType("bit");

                    b.Property<string>("marqueeBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marqueeTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("number1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("offQuotes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("plDelete")
                        .HasColumnType("time");

                    b.Property<string>("silverCoinHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("silverDifferance")
                        .HasColumnType("int");

                    b.Property<string>("whatsAppNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblContact");
                });

            modelBuilder.Entity("SL_Bullion.Models.DeleteOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dealNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("deleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("editorderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("exchange")
                        .HasColumnType("float");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("margin")
                        .HasColumnType("float");

                    b.Property<DateTime>("orderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("premium")
                        .HasColumnType("float");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("symbolId")
                        .HasColumnType("int");

                    b.Property<string>("symbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tradeType")
                        .HasColumnType("int");

                    b.Property<double>("volume")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("tblDeleteOrder");
                });

            modelBuilder.Entity("SL_Bullion.Models.Feedback", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblFeedback");
                });

            modelBuilder.Entity("SL_Bullion.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("buyPremiumGold")
                        .HasColumnType("float");

                    b.Property<double>("buyPremiumSilver")
                        .HasColumnType("float");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<bool>("isEnable")
                        .HasColumnType("bit");

                    b.Property<bool>("isTrade")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("sellPremiumGold")
                        .HasColumnType("float");

                    b.Property<double>("sellPremiumSilver")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("tblGroup");
                });

            modelBuilder.Entity("SL_Bullion.Models.GroupSymbol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("buyPremium")
                        .HasColumnType("float");

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<double>("inTotal")
                        .HasColumnType("float");

                    b.Property<bool>("isView")
                        .HasColumnType("bit");

                    b.Property<double>("oneClick")
                        .HasColumnType("float");

                    b.Property<double>("sellPremium")
                        .HasColumnType("float");

                    b.Property<double>("step")
                        .HasColumnType("float");

                    b.Property<int>("symbolId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tblGroupSymbol");
                });

            modelBuilder.Entity("SL_Bullion.Models.Hedge", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<int>("division")
                        .HasColumnType("int");

                    b.Property<int>("hedgeSymbolId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("symbolId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tblHedge");
                });

            modelBuilder.Entity("SL_Bullion.Models.HedgeInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblHedgeInfo");
                });

            modelBuilder.Entity("SL_Bullion.Models.HedgeSymbol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblHedgeSymbol");
                });

            modelBuilder.Entity("SL_Bullion.Models.Jewellery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TagNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDisplay")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblJewellery");
                });

            modelBuilder.Entity("SL_Bullion.Models.Kyc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("companyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gstNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ifsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officeMobile1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officeMobile2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("panNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partnerMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("residenceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblKyc");
                });

            modelBuilder.Entity("SL_Bullion.Models.Master", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coinEndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coinStartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("coinTradeOn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isCategory")
                        .HasColumnType("bit");

                    b.Property<bool>("isCity")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoin")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoinTrade")
                        .HasColumnType("bit");

                    b.Property<bool>("isEndUserLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("isJewellery")
                        .HasColumnType("bit");

                    b.Property<bool>("isKyc")
                        .HasColumnType("bit");

                    b.Property<bool>("isMeta")
                        .HasColumnType("bit");

                    b.Property<bool>("isOtp")
                        .HasColumnType("bit");

                    b.Property<bool>("isOtr")
                        .HasColumnType("bit");

                    b.Property<bool>("isSlider")
                        .HasColumnType("bit");

                    b.Property<int>("lastCoinDealNo")
                        .HasColumnType("int");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("startDealNo")
                        .HasColumnType("int");

                    b.Property<int>("startLoginId")
                        .HasColumnType("int");

                    b.Property<int>("symbol")
                        .HasColumnType("int");

                    b.Property<int?>("totalSlider")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("versionAndroid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("versionIos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblMaster");
                });

            modelBuilder.Entity("SL_Bullion.Models.MasterLogin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblMasterLogin");
                });

            modelBuilder.Entity("SL_Bullion.Models.OpenOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dealNo")
                        .HasColumnType("int");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("differenceRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("editorderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("exchange")
                        .HasColumnType("float");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isHedge")
                        .HasColumnType("bit");

                    b.Property<bool>("isLimit")
                        .HasColumnType("bit");

                    b.Property<string>("loginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("margin")
                        .HasColumnType("float");

                    b.Property<DateTime>("orderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("premium")
                        .HasColumnType("float");

                    b.Property<double>("premiumLimit")
                        .HasColumnType("float");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("symbolId")
                        .HasColumnType("int");

                    b.Property<string>("symbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tradeType")
                        .HasColumnType("int");

                    b.Property<double>("volume")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("tblOpenOrder");
                });

            modelBuilder.Entity("SL_Bullion.Models.OpenOrderCoin", b =>
                {
                    b.Property<int>("OpenOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpenOrderID"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DealNo")
                        .HasColumnType("bigint");

                    b.Property<double>("Exchange")
                        .HasColumnType("float");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenTradeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SymbolID")
                        .HasColumnType("int");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float");

                    b.Property<string>("TradeFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("OpenOrderID");

                    b.ToTable("tblOpenOrderCoin");
                });

            modelBuilder.Entity("SL_Bullion.Models.OpenOrderCoinHistory", b =>
                {
                    b.Property<int>("OpenOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpenOrderID"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CloseDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ClosePrice")
                        .HasColumnType("float");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DealNo")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Exchange")
                        .HasColumnType("float");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenTradeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SymbolID")
                        .HasColumnType("int");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float");

                    b.Property<string>("TradeFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("OpenOrderID");

                    b.ToTable("tblOpenOrderCoinHistory");
                });

            modelBuilder.Entity("SL_Bullion.Models.Otr", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("firmname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isOtpVerify")
                        .HasColumnType("bit");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblOtr");
                });

            modelBuilder.Entity("SL_Bullion.Models.ReferanceSymbol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<bool>("isMaster")
                        .HasColumnType("bit");

                    b.Property<bool>("isView")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblReferanceSymbol");
                });

            modelBuilder.Entity("SL_Bullion.Models.Slider", b =>
                {
                    b.Property<int>("SliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SliderId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SliderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SliderThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SliderId");

                    b.ToTable("tblSlider");
                });

            modelBuilder.Entity("SL_Bullion.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDisplay")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblSubCategory");
                });

            modelBuilder.Entity("SL_Bullion.Models.Symbol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<double>("buyCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("buyPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("changePremiumDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("digit")
                        .HasColumnType("int");

                    b.Property<double>("division")
                        .HasColumnType("float");

                    b.Property<double>("gst")
                        .HasColumnType("float");

                    b.Property<double>("gstBill")
                        .HasColumnType("float");

                    b.Property<int>("high")
                        .HasColumnType("int");

                    b.Property<string>("identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("index")
                        .HasColumnType("int");

                    b.Property<int>("initialMargin")
                        .HasColumnType("int");

                    b.Property<bool>("isBill")
                        .HasColumnType("bit");

                    b.Property<bool>("isComment")
                     .HasColumnType("bit");

                    b.Property<bool>("isTerminal")
                        .HasColumnType("bit");

                    b.Property<bool>("isTrade")
                        .HasColumnType("bit");

                    b.Property<bool>("isView")
                        .HasColumnType("bit");

                    b.Property<int>("low")
                        .HasColumnType("int");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiply")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("sellCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("sellPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<string>("symbolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("tcsBill")
                        .HasColumnType("float");

                    b.Property<double>("tdsBill")
                        .HasColumnType("float");

                    b.Property<int>("useStock")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tblSymbol");
                });

            modelBuilder.Entity("SL_Bullion.Models.SymbolSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("session")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("symbolId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tblSymbolSession");
                });

            modelBuilder.Entity("SL_Bullion.Models.UnFixOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dealNo")
                        .HasColumnType("int");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("differenceRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("editorderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("exchange")
                        .HasColumnType("float");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isHedge")
                        .HasColumnType("bit");

                    b.Property<bool>("isLimit")
                        .HasColumnType("bit");

                    b.Property<string>("loginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("margin")
                        .HasColumnType("float");

                    b.Property<DateTime>("orderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("premium")
                        .HasColumnType("float");

                    b.Property<double>("premiumLimit")
                        .HasColumnType("float");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("symbolId")
                        .HasColumnType("int");

                    b.Property<string>("symbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tradeType")
                        .HasColumnType("int");

                    b.Property<double>("volume")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("tblUnFixOrder");
                });

            modelBuilder.Entity("SL_Bullion.Models.Update", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblUpdate");
                });
#pragma warning restore 612, 618
        }
    }
}
